### ISSUE TITLE
Stuck in the menu when canceling Flux OS Controls

### ISSUE THREAD

**Issue by TechDufus** [JKTUNING/Flux-Node-Tools#12]
To reproduce...
```bash
fluxnodeview -> F -> Flux OS Controls -> Cancel
```
Getting to the above envirenment never brings me back to the command menu, or any menu for that matter... just at a blank terminal..

**Comment by JKTUNING** [comment]
I see the issue. Update incoming later today!

**Comment by JKTUNING** [comment]
Fixed with #13  - will return to benchmark screen upon exit.
