### ISSUE TITLE
Compatibility with `Ubuntu 22.04.1 LTS`

### ISSUE THREAD

**Issue by badmingtoncedric** [JKTUNING/Flux-Node-Tools#35]
Hi !

I have updated my node /w the latest Ubuntu version without errors so I suggest you remove the check condition in your script:
https://github.com/JKTUNING/Flux-Node-Tools/blob/main/flux_node_viewer.sh#L61

**Replace**
```
if [[ $(lsb_release -cs) == "jammy" || $(lsb_release -cs) == *kinetic*  ]]; then
```
**By**
```
if [[ $(lsb_release -cs) == *kinetic*  ]]; then
```

![flux-view-22_04_1_LTS](https://user-images.githubusercontent.com/4385172/213926163-c68ff206-1aad-40b7-8295-a3c7f568e6fb.png)

Best regard

**Comment by JKTUNING** [comment]
Once the support is officially added to install script I will remove it completely.

I could however change it to simply a warning on initial run of the script and continue on.

I know it is possible to run MongoDB on 22.xx but AFAIK it still isn't officially supported even from Mongo side of things.

Thanks for the feedback!

(Also as a note - support for 22.04 is being worked on to add it into Multitoolbox script installer).

**Comment by JKTUNING** [comment]
```#check opperating system version
if [[ $(lsb_release -cs) == "jammy" || $(lsb_release -cs) == *kinetic*  ]]; then
  echo -e "${SEA}WARNING: ${RED}OS version [$(lsb_release -cs)] not officially supported${NC}"
  echo -e "${SEA}Please re-image with Ubuntu Focal 20.04 Server or verify appropriate packages are installed for MongoDB"
  sleep 10
fi
```

Adding warning prompt but will continue to let application run.
